tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
        cd /workspace
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        cd $THEIA_WORKSPACE_ROOT
        aws s3 ls
        mkdir S3
        cd $THEIA_WORKSPACE_ROOT/S3
        touch create-bucket
        echo "#!/usr/bin/bash" > create-bucket
        touch list-bucket
        echo "#!/usr/bin/bash" > list-bucket
        touch delete-bucket
        echo "#!/usr/bin/bash" > delete-bucket
        touch sync
        echo "#!/usr/bin/bash" > sync
        
