#!/usr/bin/bash
echo "CREATE-BUCKET"
# Check if bucket name is provided
if [ -z "$1" ]; then
    echo "Error: Bucket name is required."
    exit 1
fi

bucket_name="$1"
region="us-east-1"  # Change this if needed

# Check if the bucket already exists
bucket_exists=$(aws s3api list-buckets --query "Buckets[?Name=='$bucket_name'].Name" --output text --region $region)

if [ "$bucket_exists" == "$bucket_name" ]; then
    echo "Bucket '$bucket_name' already exists."
else
    echo "Bucket '$bucket_name' does not exist. Creating bucket..."
    aws s3api create-bucket --bucket "$bucket_name" --region "$region" --query Location --output text
    if [ $? -eq 0 ]; then
        echo "Bucket '$bucket_name' created successfully."
    else
        echo "Failed to create bucket '$bucket_name'."
        exit 1
    fi
fi
