#!/usr/bin/bash
echo "LIST-OBJECTS"
# Check if bucket name is provided
if [ -z "$1" ]; then
    echo "Error: Bucket name is required."
    exit 1
fi

bucket_name="$1"
region="us-east-1"  # Change this if needed

# Check if the bucket already exists
bucket_exists=$(aws s3api list-buckets --query "Buckets[?Name=='$bucket_name'].Name" --output text --region $region)

if [ "$bucket_exists" == "$bucket_name" ]; then
        aws s3api list-objects --bucket $bucket_exists --query "Contents[].Key" --output json  > list-objects.json
else
    echo "Bucket '$bucket_name' doesnot exists."
fi
