#!/usr/bin/bash
echo "PUT-OBJECTS"
set -e  # Stop script on first failure
# Check if bucket name is provided
if [ -z "$1" ]; then
    echo "Error: Bucket name is required."
    exit 1
fi

bucket_name="$1"
region="us-east-1"  # Change this if needed

OUTPUT_DIR="/tmp/s3-files"

if [ -d $OUTPUT_DIR ]; then;
    rm -r "$OUTPUT_DIR"
fi

mkdir -p "$OUTPUT_DIR"

NUM_FILES=$((RANDOM%6+5))

for ((i=1; i<=NUM_FILES; i++)); do
    # Generate the File 
    echo "FIRST FILE" > "$OUTPUT_DIR/FILE_$i"
done 

echo "$NUM_FILES Created"

tree "$OUTPUT_DIR"

# Check if the bucket already exists
bucket_exists=$(aws s3api list-buckets --query "Buckets[?Name=='$bucket_name'].Name" --output text --region $region)

if [ "$bucket_exists" == "$bucket_name" ]; then
        aws s3api put-objects -- bucket bucket_exists --query
    aws s3api delete-bucket --bucket "$bucket_name" --region "$region" --output text
    if [ $? -eq 0 ]; then
        echo "Bucket '$bucket_name' deleted successfully."
    else
        echo "Failed to delete bucket '$bucket_name'."
        exit 1
    fi
else
    echo "Bucket '$bucket_name' doesnot exists."
fi
