AWSTemplateFormatVersion: "2010-09-09"
Resources:
  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: manojcfnawsbucket
      # Bucket name is not mandatory, It will generate the bucket name randomly, if not provided.